export enum OPCODES {
  D1_CHANNEL_FADER = 0,
  D1_CFX = 1,
  D1_LOW_FILTER = 2,
  D1_MID_FILTER = 3,
  D1_HIGH_FILTER = 4,
  D1_TRIM = 5,
  D1_TEMPO = 6,
  D1_SONG_ID = 7,
  D1_IS_PLAYING = 8,
  D1_CURRENT_TIME = 9,
  D2_CHANNEL_FADER = 10,
  D2_CFX = 11,
  D2_LOW_FILTER = 12,
  D2_MID_FILTER = 13,
  D2_HIGH_FILTER = 14,
  D2_TRIM = 15,
  D2_TEMPO = 16,
  D2_SONG_ID = 17,
  D2_IS_PLAYING = 18,
  D2_CURRENT_TIME = 19,
}

export type TCP_OPCODES =
  | OPCODES.D1_IS_PLAYING
  | OPCODES.D1_SONG_ID
  | OPCODES.D2_IS_PLAYING
  | OPCODES.D2_SONG_ID;
export type UDP_OPCODES =
  | OPCODES.D1_CHANNEL_FADER
  | OPCODES.D1_CFX
  | OPCODES.D1_LOW_FILTER
  | OPCODES.D1_MID_FILTER
  | OPCODES.D1_HIGH_FILTER
  | OPCODES.D1_TRIM
  | OPCODES.D1_TEMPO
  | OPCODES.D1_CURRENT_TIME
  | OPCODES.D2_CHANNEL_FADER
  | OPCODES.D2_CFX
  | OPCODES.D2_LOW_FILTER
  | OPCODES.D2_MID_FILTER
  | OPCODES.D2_HIGH_FILTER
  | OPCODES.D2_TRIM
  | OPCODES.D2_TEMPO
  | OPCODES.D2_CURRENT_TIME;
